# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SfhE7YIE9yfdiaAFY1elxegQXqqwQHx1
"""

import pickle
import sklearn

# Load the trained model from the .pkl file
with open('knn_model.pkl', 'rb') as file:
    classifier = pickle.load(file)
new_data_point = [[79, 45, 43, 25, 79, 7, 187]]  # Example new data point
#79	45	43	25.71901283	79.15532398	7.171054239	187.1735424
predicted_crop = classifier.predict((new_data_point))
print(predicted_crop)